apiVersion: apps/v1
kind: Deployment
metadata:
  # Имя инстанса
  name: example-app
spec:
  # Кол-во подов
  replicas: 4
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: web-app
        image: name:tag
        ports:
        - name: liveness-port
          containerPort: 8080
          hostPort: 8080
        # Проверяет готовность пода
        livenessProbe:
          httpGet:
            path: /healthz
            port: liveness-port
          # Кол-во ошибок
          failureThreshold: 3
          # Период проверки
          periodSeconds: 10
          # Сброс счётчика ошибок
          successThreshold: 1
        # Проверяет доступность приложения с максимальным дилэем (3*4=12) 12 секунд
        startupProbe:
          httpGet:
            path: /healthz
            port: liveness-port
          failureThreshold: 3
          periodSeconds: 4
          
        resources:
          #  Резервируемые ресурсы пода на ноде
          requests:
            cpu: 500m
            memory: 128M
          # Лимиты пода
          limits:
            cpu: 500m
            memory: 128M
          # Благодаря одинаковым параметрам request и limits, QoS приоритет будет Guaranteed \
          # эти поды будут иметь самый высокий приоритет в kubernetes
